---
name: Alien-scriptaculous
version: 1.7.1.2_03
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: installing and finding script.aculo.us
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Alien::Prototype: 1.5.1.2
  perl: 5.6.0
build_requires:
  Archive::Tar: 0
  Test::Exception: 0
provides:
  Alien::scriptaculous:
    file: lib/Alien/scriptaculous.pm
    version: 1.7.1.2_03
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
