---
name: Alien-scriptaculous
version: 1.000
author:
  - "Graham TerMarsch (cpan@howlingfrog.com)"
abstract: installing and finding script.aculo.us
license: perl
requires:
  Archive::Tar: 0
  Test::Exception: 0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Alien::scriptaculous:
    file: lib/Alien/scriptaculous.pm
    version: 1.000
resources:
  license: http://dev.perl.org/licenses/
